apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: FastAPI Monitor
    type: prometheus
    access: proxy
    url: http://localhost:8001/metrics
    editable: true
